Update nginx to 1.20.2
BREAKING CHANGE: Nginx is updated to version 1.20.2. As part of this update, we are switching from the default Alpine nginx package to the nginx.org package. The nginx.org package is only available for aarch64 and amd64. Therefore, the following CPU architectures are no longer supported:
- armhf
- armv7
- i386

Other noteworth changes:

- Bump nginx-proxy-waf version to 4.0.0
- Bump Alpine version to 3.14
- Pull builder image from ghcr for nging-proxy-waf build

diff --git a/nginx_proxy/Dockerfile b/nginx_proxy/Dockerfile
--- a/nginx_proxy/Dockerfile
+++ b/nginx_proxy/Dockerfile
@@ -1,21 +1,34 @@
 ARG BUILD_FROM
 ARG BUILD_ARCH
 ARG BUILD_MODSECURITY_VERSION
+ARG NGINX_VERSION 1.20.2
+ARG PKG_RELEASE   1
 
-FROM jhampdbre/${BUILD_ARCH}-nginx-116-modsecurity:${BUILD_MODSECURITY_VERSION} as build_modsecurity
+FROM jhampdbre/${BUILD_ARCH}-nginx-${NGINX_VERSION}-modsecurity:${BUILD_MODSECURITY_VERSION} as build_modsecurity
 
 FROM $BUILD_FROM
 
 # Setup base
-RUN apk add --no-cache \
+RUN set -x \
+    && KEY_SHA512="e7fa8303923d9b95db37a77ad46c68fd4755ff935d0a534d26eba83de193c76166c68bfe7f65471bf8881004ef4aa6df3e34689c305662750c0172fca5d8552a *stdin" \
+    && apk add --no-cache \
     geoip \
     libmaxminddb \
     libstdc++ \
     libxml2 \
     lmdb \
     yajl \
-    nginx \
     openssl \
+    && wget -O /tmp/nginx_signing.rsa.pub https://nginx.org/keys/nginx_signing.rsa.pub \
+    && if [ "$(openssl rsa -pubin -in /tmp/nginx_signing.rsa.pub -text -noout | openssl sha512 -r)" = "$KEY_SHA512" ]; then \
+    echo "key verification succeeded!"; \
+    mv /tmp/nginx_signing.rsa.pub /etc/apk/keys/; \
+    else \
+    echo "key verification failed!"; \
+    exit 1; \
+    fi \
+    && apk add -X "https://nginx.org/packages/alpine/v$(egrep -o '^[0-9]+\.[0-9]+' /etc/alpine-release)/main" --no-cache ${NGINX_VERSION}-r${PKG_RELEASE} \
+    ;; \
     && mkdir /etc/nginx/modsec
 
 # Copy owasp-modsecurity-crs and modsecurity from the build image
